server:
  port: 20000
  servlet:
    session:
      timeout: 30m

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.153:8848
  application:
    name: gulimall-auth
  thymeleaf:
    cache: false
  redis:
    host: 192.168.135.128
    port: 6379
  session:
    store-type: redis
    redis:
      flush-mode: on_save



gulimall:
  oauth2:
    appId: 3512885621
    appSecret: 05995f8d5f8603da12c00cce9829ef6e

